In [1]:
import pandas as pd
from scipy.stats import chi2_contingency

In [2]:
# Creating sample data with a slight association
data = {
    "education_level": (
        ["High School"] * 40 +
        ["College"] * 40 +
        ["Graduate"] * 40
    ),
    "homeowner": (
        ["Yes"] * 10 + ["No"] * 30 +     # High School
        ["Yes"] * 20 + ["No"] * 20 +     # College
        ["Yes"] * 30 + ["No"] * 10       # Graduate
    )
}

df = pd.DataFrame(data)
df.head()

  education_level homeowner
0     High School       Yes
1     High School       Yes
2     High School       Yes
3     High School       Yes
4     High School       Yes

In [3]:
df["education_level"].value_counts(), df["homeowner"].value_counts()

(education_level
 High School    40
 College        40
 Graduate       40
 Name: count, dtype: int64,
 homeowner
 Yes    60
 No     60
 Name: count, dtype: int64)

In [4]:
contingency_table = pd.crosstab(df["education_level"], df["homeowner"])
contingency_table

homeowner        No  Yes
education_level
College          20   20
Graduate         10   30
High School      30   10

In [5]:
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

print("Chi-Square Statistic:", chi2_stat)
print("P-value:", p_value)
print("Degrees of Freedom:", dof)

Chi-Square Statistic: 20.0
P-value: 4.539992976248486e-05
Degrees of Freedom: 2

In [6]:
expected_df = pd.DataFrame(
    expected,
    index=contingency_table.index,
    columns=contingency_table.columns
)

expected_df

homeowner          No   Yes
education_level
College          20.0  20.0
Graduate         20.0  20.0
High School      20.0  20.0

In [7]:
alpha = 0.05

if p_value < alpha:
    print("Reject the Null Hypothesis")
    print("There IS a statistically significant relationship between education level and homeownership.")
else:
    print("Fail to Reject the Null Hypothesis")
    print("There is NO statistically significant relationship between education level and homeownership.")

Reject the Null Hypothesis
There IS a statistically significant relationship between education level and homeownership.